query culturaDesenvolvida(
  $currentDate: String
  $periodSelected: String
  $id: ID
) {
  culturaDesenvolvidas(
    date: $currentDate
    type: $periodSelected
    culturaDesenvolvidaId: $id
  ) {
    id
    AreaTerrenoHectares
    DataInicio
    DataColheita
    QtdColhida
    Unidade
    Agricultor {
      id
      Nome
    }
    Cultura {
      id
      DescrCultura
      QtdEstimadaPorHectare
      Und
    }
  }
}
