mutation UpdateCliente($nome: String!, $index: ID!) {
  updateCliente(data: { NomeCliente: $nome }, where: { id: $index }) {
    id
    NomeCliente
    Agricultor {
      id
      Nome
      Email
    }
  }
}
