mutation UpdateUsoInsumoPrevisto(
  $quantidade: Float!
  $culturaEtapaId: ID!
  $insumoId: ID!
  $id: ID!
) {
  updateUsoInsumoPrevisto(
    where: { id: $id }
    data: {
      Qtd: $quantidade
      CulturaEtapa: { connect: { id: $culturaEtapaId } }
      Insumo: { connect: { id: $insumoId } }
    }
  ) {
    id
    Qtd
    CulturaEtapa {
      id
      DescrEtapa
    }
    Insumo {
      id
      DescrInsumo
    }
  }
}
