mutation CreateCultura($name: String!, $quantidade: Float!, $unidade: String!) {
  createCultura(
    DescrCultura: $name
    QtdEstimadaPorHectare: $quantidade
    Und: $unidade
  ) {
    id
    DescrCultura
    QtdEstimadaPorHectare
    Und
    Agricultor {
      id
      Nome
      Email
    }
  }
}
