mutation DeleteDespesa($id: ID) {
  deleteDespesaRealizada(where: { id: $id }) {
    id
    DescrDetalhada
    Data
    Valor
    TipoDespesa {
      id
      DescrTipoDespesa
    }
    Agricultor {
      id
      Nome
    }
  }
}
