mutation UpdateDespesa(
  $index: ID!
  $date: DateTime!
  $descricao: String!
  $valor: Float!
  $tipo: ID!
) {
  updateDespesaRealizada(
    where: { id: $index }
    data: {
      DescrDetalhada: $descricao
      Data: $date
      Valor: $valor
      TipoDespesa: { connect: { id: $tipo } }
    }
  ) {
    id
    DescrDetalhada
    Data
    Valor
    TipoDespesa {
      id
      DescrTipoDespesa
    }
    Agricultor {
      id
      Nome
    }
  }
}
