mutation UpdateInsumo(
  $index: ID!
  $descricao: String!
  $valor: Float!
  $unidade: String!
  $tipo: ID!
) {
  updateInsumo(
    where: { id: $index }
    data: {
      DescrInsumo: $descricao
      PrecoUnit: $valor
      Und: $unidade
      TipoInsumo: { connect: { id: $tipo } }
    }
  ) {
    id
    DescrInsumo
    PrecoUnit
    Und
    TipoInsumo {
      id
      NomeTipo
    }
    Agricultor {
      id
      Nome
      Email
    }
  }
}
